### PR TITLE
Use the generic fcntl.h header

### PR DESCRIPTION
**Pull request by mickflemm**
Currently the fcntl.h header uses different macros from those on
upstream Linux. On upstream Linux there is no arch-specific
fcntl.h, the generic one is used. As a result various syscalls using
these macros fail, an example being BusyBox where any call to
opendir() will fail because O_DIRECTORY id is different between
the headers used here (probably coming from arm64) and the generic
headers used by the kernel. Simply delete the arch-specific fcntl.h
and let musl use the generic header as well.

### CODE REVIEW

**Comment by mickflemm** [comment]
@michaeljclark , @palmer-dabbelt could you please review this ?

Thanks for your time !

**Comment by palmer-dabbelt** [comment]
I think these should only exist on 32-bit.

**Comment by ddevault** [comment]
I was experiencing these issues on riscv64, this patch solved them.

**Comment by michaelforney** [comment]
I think this commit breaks `F_GETLK`, `F_SETLK`, and `F_SETLKW` on all 32-bit architectures that use the generic `fcntl.h` header (including riscv32 and i386). As described in https://www.openwall.com/lists/musl/2018/10/18/1, musl defines `struct flock` to match the kernel's `struct flock64` (since musl's `off_t` is always 64-bit). But, defining `F_GETLK` as 5 will cause the kernel to treat the argument as its `struct flock` with 32-bit `off_t`.

Additionally, defining `F_GETLK64`, `F_SETLK64` and `F_SETLKW64` as 12, 13 and 14 on 64-bit architectures that use the generic `fcntl.h` header (for example riscv64 after this patch series) will cause `EINVAL` on any uses of `fcntl` with those commands.

As suggested in the above mail, I think we should only drop `arch/riscv32/bits/fcntl.h`, and leave `arch/riscv64/bits/fcntl.h` after fixing its constants. Maybe there is some way to make `arch/generic/bits/fcntl.h` work for both 32-bit and 64-bit, but I think this is the simplest for now.

**Comment by mickflemm** [comment]
> I think this commit breaks `F_GETLK`, `F_SETLK`, and `F_SETLKW` on all 32-bit architectures that use the generic `fcntl.h` header (including riscv32 and i386). As described in https://www.openwall.com/lists/musl/2018/10/18/1, musl defines `struct flock` to match the kernel's `struct flock64` (since musl's `off_t` is always 64-bit). But, defining `F_GETLK` as 5 will cause the kernel to treat the argument as its `struct flock` with 32-bit `off_t`.
> 
> Additionally, defining `F_GETLK64`, `F_SETLK64` and `F_SETLKW64` as 12, 13 and 14 on 64-bit architectures that use the generic `fcntl.h` header (for example riscv64 after this patch series) will cause `EINVAL` on any uses of `fcntl` with those commands.
> 
> As suggested in the above mail, I think we should only drop `arch/riscv32/bits/fcntl.h`, and leave `arch/riscv64/bits/fcntl.h` after fixing its constants. Maybe there is some way to make `arch/generic/bits/fcntl.h` work for both 32-bit and 64-bit, but I think this is the simplest for now.

So the *64 variants of the F_GETLK/SETLK/SETLKW macros are Linux-specific and are not defined on POSIX so the caller is not expected to use them (according to the man page "these details can be ignored by applications using glibc, whose fcntl() wrapper function transparently employs the more recent system call where it is available"). You may notice that src/fcntl/fcntl.c doesn't use them, so there is no issue on riscv64 since no one is going to do the system call with F_GETLK64 for example.

With the current approach (without this patch), F_GETLK/SETLK/SETLKW are defined by default on the generic header to have the same values as with the *64 variants. That only makes sense for 32bit architectures where the *64 variants need to be used in order for the kernel to return loff_t based structures (with 64bit integers). On 64bit architectures the *64 variants are invalid and we get EINVAL.

I've tested musl on riscv64 with the above patches and it works as expected. You may try it as well (to get an idea here is the kernel's part -> https://elixir.bootlin.com/linux/latest/source/fs/fcntl.c).

So the current approach fails on 64bit archs and the patches I introduced work on 64bits but fail on 32bit archs. A proper solution would be to use LONG_BIT from arch/../bits/limits.h and override F_GETLK/SETLK/SETLKW accordingly. I'll add another patch to the series to address this issue.

**Comment by michaelforney** [comment]
> So the *64 variants of the F_GETLK/SETLK/SETLKW macros are Linux-specific and are not defined on POSIX so the caller is not expected to use them. You may notice that src/fcntl/fcntl.c doesn't use them, so there is no issue on riscv64 since no one is going to do the system call with F_GETLK64 for example.

Just because something is not specified by POSIX doesn't mean that there aren't programs in the wild that use it. How can you be sure that there isn't any software out there that calls `fcntl` with `F_SETLK64` and a `struct flock64`?

> With the current approach (without this patch), F_GETLK/SETLK/SETLKW are defined by default on the generic header to have the same values as with the *64 variants. That only makes sense for 32bit architectures where the *64 variants need to be used in order for the kernel to return loff_t based structures (with 64bit integers). On 64bit architectures the *64 variants are invalid and we get EINVAL.

My point is, on current glibc and musl, the *64 variants of the constants (as well as `struct flock64`) are defined and work regardless of target architecture. Currently, for all architectures musl has `F_GETLK == F_GETLK64`. This patch makes riscv64 the only architecture where that is not true (since all other 64-bit architectures provide their own `fcntl.h`).

Note that glibc also defines the *64 constants as 5, 6, and 7 on riscv64:
https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/riscv/bits/fcntl.h;h=40588c4e9e6ec67977ee105cdf90564406e50e8b;hb=HEAD#l31

**Comment by mickflemm** [comment]
> > So the *64 variants of the F_GETLK/SETLK/SETLKW macros are Linux-specific and are not defined on POSIX so the caller is not expected to use them. You may notice that src/fcntl/fcntl.c doesn't use them, so there is no issue on riscv64 since no one is going to do the system call with F_GETLK64 for example.
> 
> Just because something is not specified by POSIX doesn't mean that there aren't programs in the wild that use it. How can you be sure that there isn't any software out there that calls `fcntl` with `F_SETLK64` and a `struct flock64`?
> 

As the man page for fcntl says the applications are expected to use the libc wrapper, if an application uses the syscall API directly they are on their own, you'll notice that the *64 variants are only mentioned on a comment, not as valid flags to be used by the caller. This makes sense because they are invalid for 64bit architectures and the C api is expected to be architecture agnostic. If you see the kernel source (see the link I posted above), the fcntl64 system call, where the flock64 struct is used, is only defined when 'BITS_PER_LONG == 32', on 64bit architectures it doesn't exist, since the fcntl syscall always returns int64-based structures.

Musl itself doesn't use the *64 variants...
https://github.com/riscv/riscv-musl/blob/riscv-musl-1.1.20/src/fcntl/fcntl.c
it expects for F_GETLK/SETLK/SETLKW to be equal to the *64 values on the fcntl.h header, for 32bit architectures, for this to work "transparently".

> > With the current approach (without this patch), F_GETLK/SETLK/SETLKW are defined by default on the generic header to have the same values as with the *64 variants. That only makes sense for 32bit architectures where the *64 variants need to be used in order for the kernel to return loff_t based structures (with 64bit integers). On 64bit architectures the *64 variants are invalid and we get EINVAL.
> 
> My point is, on current glibc and musl, the *64 variants of the constants (as well as `struct flock64`) are defined and work regardless of target architecture. Currently, for all architectures musl has `F_GETLK == F_GETLK64`. This patch makes riscv64 the only architecture where that is not true (since all other 64-bit architectures provide their own `fcntl.h`).
> 

Please check out the code again, `F_GETLK == F_GETLK64` only makes sense for 32bit architectures, in cases where the C library always uses the flock64 structure (for largefiles etc). On 64bit architectures the system call will always return a structure with 64bit integers anyway and using the *64 values will result an invalid argument when performing the system call (see do_fcntl on the link to the kernel source above).

We use the generic header on the Linux kernel (that works for both 32 and 64bit architectures) so I don't see a reason to use a custom header on musl that's 99% duplicated code just because the generic musl header doesn't handle 64bit architectures properly. Instead we should fix the generic header on musl to handle both 32 and 64bit architectures.

> Note that glibc also defines the *64 constants as 5, 6, and 7 on riscv64:
> https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/riscv/bits/fcntl.h;h=40588c4e9e6ec67977ee105cdf90564406e50e8b;hb=HEAD#l31

That also happens here (see the second patch), it's there for applications that by mistake use the *64 variants on 64bit architectures, so that they keep working. Normally the *64 variants shoudln't even be defined for 64bit architectures since they are not part of the API (the fcntl64 syscall doesn't exist).

**Comment by michaelforney** [comment]
I think you are confusing the `F_*` constants defined by the kernel, and those defined by libc (in this file). Yes, there is no `F_SETLK64` defined in the kernel headers on 64-bit architectures. However, there *is* a `F_SETLK64` defined by libc (passed to the `fcntl` libc function, *not* the `SYS_fcntl` system call).

> As the man page for fcntl says the applications are expected to use the libc wrapper, if an application uses the syscall API directly they are on their own, you'll notice that the *64 variants are only mentioned on a comment, not as valid flags to be used by the caller.

I'm not talking about applications using the syscall directly, but applications using the `fcntl` libc function with the `F_*64` commands (along with `struct flock64`), which is part of the transitional extensions to POSIX enabling large file support ([LFS64](http://www.unix.org/version2/whatsnew/lfs20mar.html#3.1.2.4)). These `fcntl` commands are exposed by libc by defining [`_LARGEFILE64_SOURCE`](https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html#index-_005fLARGEFILE64_005fSOURCE) in your application.

Yes, this is an old and obsolete interface, but musl does provide it, and so it needs to provide definitions of `F_GETLK64`, `F_SETLK64`, `F_SETLKW64`, and `struct flock64` that work with the libc `fcntl` function. This is why musl defines them to match the corresponding non-64 constants unconditionally (http://git.musl-libc.org/cgit/musl/commit/?id=78c6d30fd3bb13f5fc6e1ad42675fe5475a87641).

> We use the generic header on the Linux kernel (that works for both 32 and 64bit architectures) so I don't see a reason to use a custom header on musl that's 99% duplicated code just because the generic musl header doesn't handle 64bit architectures properly. Instead we should fix the generic header on musl to handle both 32 and 64bit architectures.

This custom header is only 38 lines long, so not much duplication. I agree it would be nice if the generic header worked for both 32-bit and 64-bit architectures (several existing architecture-specific `fcntl.h` headers could be deleted in that case), but I think this is a separate issue and is outside the scope of the musl RISC-V port.

**Comment by mickflemm** [comment]
I added a patch for the generic header to work on both 32 and 64bit archs, using the LONG_BIT from bits/limits.h.

**Comment by ddevault** [comment]
Tested the new patch on riscv64, works :+1:

**Comment by ddevault** [comment]
Thanks!

**Comment by richfelker** [comment]
At present, the generic fcntl bits header is only usable for 32-bit archs, as it does not have access to anything to determine whether the definitions for 32-bit or 64-bit archs should be used. It might be nice to fix this, but it's orthogonal to getting the riscv port merged. Can we go forward with a plan for riscv64 to use its own version of the bits header for now, and possibly clean this up later? I'd really like to get any remaining problems identified and resolved so we can merge it rather than introducing new breakage from things like this? The current state of the tree is not mergable because LONG_BIT is not in the namespace fcntl.h can expose, and bits/* headers are not protected by inclusion guards and are not permitted to be included anywhere but from the header they go with (which has its own inclusion guards).

**Comment by ddevault** [comment]
The riscv64 port is nigh-unusable without this patch. If it's not suitable, I'm not comfortable trying to upstream it without solving the underlying problem.

**Comment by richfelker** [comment]
Adding `arch/riscv64/bits/fcntl.h` with the right definitions and removing the changes to the generic one should work.

**Comment by michaelforney** [comment]
> Adding `arch/riscv64/bits/fcntl.h` with the right definitions and removing the changes to the generic one should work.

This is exactly what my patch from the initial riscv review thread did:
https://github.com/michaelforney/musl/commit/dd59ec7eba1f32b865568ea9196be6ff5adb8717

Perhaps you could just apply that fix instead?

**Comment by richfelker** [comment]
I think that looks right.

**Pull request merged**
